CREATE USER IF NOT EXISTS "ROOT" SALT '8db2c566fa10d736' HASH '3138c97d0fc9bc8449f672153df1bd5510cff40ca41edf602d7c67bb7dd43fa0' ADMIN;
CREATE SEQUENCE "PUBLIC"."CATEGORY_ID_GEN" START WITH 100 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."PRODUCT_SIMPLE_ID_GEN" START WITH 100 INCREMENT BY 50;
CREATE CACHED TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP,
    "CREATED_BY" VARCHAR(255),
    "MODIFIED_AT" TIMESTAMP,
    "MODIFIED_BY" VARCHAR(255),
    "TITLE" VARCHAR(255) NOT NULL,
    "URL" VARCHAR(255) NOT NULL
);
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");

CREATE CACHED TABLE "PUBLIC"."PRODUCT_SIMPLE"(
    "DTYPE" VARCHAR(31) NOT NULL SELECTIVITY 1,
    "ID" BIGINT NOT NULL SELECTIVITY 100,
    "CREATED_AT" TIMESTAMP SELECTIVITY 1,
    "CREATED_BY" VARCHAR(255) SELECTIVITY 1,
    "MODIFIED_AT" TIMESTAMP SELECTIVITY 1,
    "MODIFIED_BY" VARCHAR(255) SELECTIVITY 1,
    "ACTUAL_STORAGE" INTEGER SELECTIVITY 4,
    "CATEGORY" VARCHAR(255) NOT NULL SELECTIVITY 1,
    "DESCRIPTION" VARCHAR(255) SELECTIVITY 100,
    "IMAGE_URL_SMALL" VARCHAR(255) SELECTIVITY 1,
    "NAME" VARCHAR(255) NOT NULL SELECTIVITY 92,
    "ORDER_STORAGE" INTEGER SELECTIVITY 4,
    "PRICE" DECIMAL(19, 2) NOT NULL SELECTIVITY 99,
    "RATE" VARCHAR(255) SELECTIVITY 64,
    "SALES" INTEGER SELECTIVITY 96,
    "IMAGE_URL_LARGE" VARCHAR(255) SELECTIVITY 1,
    "SELECTED_OPTIONS" VARCHAR(10000) SELECTIVITY 82,
    "SPECIFICATION" VARCHAR(255) SELECTIVITY 100
);
ALTER TABLE "PUBLIC"."PRODUCT_SIMPLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
